"""Add description column to montant table

Revision ID: 22cde61fde27
Revises: 
Create Date: 2024-08-29 17:25:50.129911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22cde61fde27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('montant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.alter_column('value',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('montant', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('description')

    # ### end Alembic commands ###
